package md.victordov.lab.vo;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profesor generated by hbm2java
 */
@Entity
@Table(name = "profesor", catalog = "uni2_4t")
public class Profesor implements java.io.Serializable {

	private Integer PId;
	private String nume;
	private String prenume;
	private String adresa;
	private Set<Curs> curses = new HashSet<Curs>(0);

	public Profesor() {
	}

	public Profesor(String nume, String prenume, String adresa) {
		this.nume = nume;
		this.prenume = prenume;
		this.adresa = adresa;
	}

	public Profesor(String nume, String prenume, String adresa, Set<Curs> curses) {
		this.nume = nume;
		this.prenume = prenume;
		this.adresa = adresa;
		this.curses = curses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "p_id", unique = true, nullable = false)
	public Integer getPId() {
		return this.PId;
	}

	public void setPId(Integer PId) {
		this.PId = PId;
	}

	@Column(name = "nume", nullable = false, length = 30)
	public String getNume() {
		return this.nume;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}

	@Column(name = "prenume", nullable = false, length = 30)
	public String getPrenume() {
		return this.prenume;
	}

	public void setPrenume(String prenume) {
		this.prenume = prenume;
	}

	@Column(name = "adresa", nullable = false, length = 40)
	public String getAdresa() {
		return this.adresa;
	}

	public void setAdresa(String adresa) {
		this.adresa = adresa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profesor")
	public Set<Curs> getCurses() {
		return this.curses;
	}

	public void setCurses(Set<Curs> curses) {
		this.curses = curses;
	}

}
