package md.victordov.lab.vo;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "uni2_4t")
public class Student implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer SId;
	private String nume;
	private String prenume;
	private String grupa;
	private String email;
	private String telFix;
	private Set<StudCurs> studCurses = new HashSet<StudCurs>(0);

	public Student() {
	}

	public Student(String nume, String prenume, String grupa, String email,
			String telFix) {
		this.nume = nume;
		this.prenume = prenume;
		this.grupa = grupa;
		this.email = email;
		this.telFix = telFix;
	}

	public Student(String nume, String prenume, String grupa, String email,
			String telFix, Set<StudCurs> studCurses) {
		this.nume = nume;
		this.prenume = prenume;
		this.grupa = grupa;
		this.email = email;
		this.telFix = telFix;
		this.studCurses = studCurses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "s_id", unique = true, nullable = false)
	public Integer getSId() {
		return this.SId;
	}

	public void setSId(Integer SId) {
		this.SId = SId;
	}

	@Column(name = "nume", nullable = false, length = 30)
	public String getNume() {
		return this.nume;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}

	@Column(name = "prenume", nullable = false, length = 30)
	public String getPrenume() {
		return this.prenume;
	}

	public void setPrenume(String prenume) {
		this.prenume = prenume;
	}

	@Column(name = "grupa", nullable = false, length = 15)
	public String getGrupa() {
		return this.grupa;
	}

	public void setGrupa(String grupa) {
		this.grupa = grupa;
	}

	@Column(name = "email", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telFix", nullable = false, length = 20)
	public String getTelFix() {
		return this.telFix;
	}

	public void setTelFix(String telFix) {
		this.telFix = telFix;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<StudCurs> getStudCurses() {
		return this.studCurses;
	}

	public void setStudCurses(Set<StudCurs> studCurses) {
		this.studCurses = studCurses;
	}

}