package md.victordov.lab.vo;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Universitate generated by hbm2java
 */
@Entity
@Table(name = "universitate", catalog = "uni2_4t")
public class Universitate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer UId;
	private String numeUniver;
	private String adresa;
	private String telefon;
	private Set<Curs> curses = new HashSet<Curs>(0);

	public Universitate() {
	}

	public Universitate(String numeUniver, String adresa, String telefon) {
		this.numeUniver = numeUniver;
		this.adresa = adresa;
		this.telefon = telefon;
	}

	public Universitate(String numeUniver, String adresa, String telefon,
			Set<Curs> curses) {
		this.numeUniver = numeUniver;
		this.adresa = adresa;
		this.telefon = telefon;
		this.curses = curses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "u_id", unique = true, nullable = false)
	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	@Column(name = "nume_univer", nullable = false, length = 30)
	public String getNumeUniver() {
		return this.numeUniver;
	}

	public void setNumeUniver(String numeUniver) {
		this.numeUniver = numeUniver;
	}

	@Column(name = "adresa", nullable = false, length = 40)
	public String getAdresa() {
		return this.adresa;
	}

	public void setAdresa(String adresa) {
		this.adresa = adresa;
	}

	@Column(name = "telefon", nullable = false, length = 30)
	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "universitate")
	public Set<Curs> getCurses() {
		return this.curses;
	}

	public void setCurses(Set<Curs> curses) {
		this.curses = curses;
	}

}